/**
 * GET /api/twenty-bridge/export-proposal-pdf?estimateId=<uuid>
 *
 * Bridge endpoint for Twenty CRM AI skill to export the exact same ANC-branded
 * proposal PDF generated by rag2.
 * This pulls the estimate + linked lines from Twenty REST, maps them to a Proposal
 * payload, and runs them through generateProposalPdfServiceV2.
 */

import { NextRequest, NextResponse } from "next/server";
import { generateProposalPdfServiceV2 } from "@/services/proposal/server/generateProposalPdfServiceV2";
import { log } from "@/lib/logger";

export const dynamic = "force-dynamic";
export const maxDuration = 300;

const TWENTY_BASE = "https://abc-twenty.izcgmb.easypanel.host";
const TWENTY_API_KEY = process.env.TWENTY_API_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkM2ZiYzI5YS1hNjM1LTQ4YjctOWQ2ZS0yNTA5NDE2NzdmZDAiLCJ0eXBlIjoiQVBJX0tFWSIsIndvcmtzcGFjZUlkIjoiZDNmYmMyOWEtYTYzNS00OGI3LTlkNmUtMjUwOTQxNjc3ZmQwIiwiaWF0IjoxNzc0ODEwNDkyLCJleHAiOjQ5Mjg0MTA0ODcsImp0aSI6IjYxMGEzMWEzLTJhMDgtNDM5MC1iMTU1LTFkN2M3NzY5Y2QxOSJ9.nzknS-bBNuf7y3LUCv2xEa5-9xuJNHBK3GalJwWK3eA";

async function twentyFetch(path: string, init?: RequestInit): Promise<any> {
  const res = await fetch(`${TWENTY_BASE}/rest/${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${TWENTY_API_KEY}`,
      "Content-Type": "application/json",
      ...(init?.headers || {}),
    },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Twenty ${res.status}: ${body.slice(0, 300)}`);
  }
  return res.json();
}

export async function GET(request: NextRequest) {
  const estimateId = request.nextUrl.searchParams.get("estimateId");
  if (!estimateId) {
    return NextResponse.json({ error: "estimateId query parameter is required" }, { status: 400 });
  }

  try {
    const estRes = await twentyFetch(`estimates/${encodeURIComponent(estimateId)}`);
    const estimate = estRes?.data?.estimate;
    if (!estimate) {
      return NextResponse.json({ error: "Estimate not found in Twenty" }, { status: 404 });
    }

    const lineRes = await twentyFetch(`estimateLines?filter=estimateId[eq]:${estimateId}&limit=200`);
    let lines: any[] = lineRes?.data?.estimateLines || [];

    const uniqueProductIds = Array.from(new Set(lines.map((l: any) => l.ledProductId).filter(Boolean)));
    const ledProductNameById = new Map<string, string>();
    await Promise.all(
      uniqueProductIds.map(async (pid: any) => {
        try {
          const r = await twentyFetch(`ledProducts/${encodeURIComponent(pid)}`);
          const p = r?.data?.ledProduct;
          if (p?.displayName || p?.name) {
            ledProductNameById.set(pid, p.displayName || p.name);
          }
        } catch {
        }
      })
    );

    // Map to formPayload
    const formPayload = {
        sender: {
            name: "ANC Support",
            title: "Support",
            company: "ANC",
            address: "",
            zipCode: "",
            city: "",
            country: "",
            email: "",
            phone: "",
            customInputs: []
        },
        receiver: {
            name: estimate.clientName || "",
            address: "",
            zipCode: "",
            city: "",
            country: "",
            email: "",
            phone: "",
            customInputs: [],
        },
        details: {
            proposalLogo: "",
            proposalId: estimate.id,
            proposalName: estimate.projectName || estimate.name || "Twenty Estimate",
            proposalNumber: estimate.id.slice(-8).toUpperCase(),
            proposalDate: estimate.createdAt ? new Date(estimate.createdAt).toISOString().split("T")[0] : "",
            dueDate: "",
            items: [],
            currency: "USD",
            exchangeRate: 1,
            language: "English",
            taxDetails: { amount: 0, amountType: "amount", taxID: "" },
            discountDetails: { amount: 0, amountType: "amount" },
            shippingDetails: { cost: 0, costType: "amount" },
            paymentInformation: { bankName: "", accountName: "", accountNumber: "" },
            additionalNotes: "",
            paymentTerms: "50% on Deposit, 40% on Mobilization, 10% on Substantial Completion",
            totalAmountInWords: "",
            documentType: "First Round",
            pricingType: "Budget",
            documentMode: "BUDGET",
            pdfTemplate: 5,
            subTotal: 0,
            totalAmount: 0,
            overheadRate: Number(estimate.overheadRate) || 0.10,
            profitRate: Number(estimate.profitRate) || 0.05,
            screens: lines.map((s: any) => ({
                id: s.id,
                name: s.displayName || s.name || "Display",
                externalName: "",
                customDisplayName: "",
                group: "",
                pitchMm: Number(s.pitchMm) || 0,
                widthFt: Number(s.widthFt) || 0,
                heightFt: Number(s.heightFt) || 0,
                brightness: "",
                hiddenFromSpecs: false,
                quantity: Number(s.quantity) || 1,
                serviceType: "",
                formFactor: "",
                lineItems: [],
            })),
            internalAudit: {},
            clientSummary: {},
            mirrorMode: undefined,
            calculationMode: "INTELLIGENCE",
            taxRateOverride: 0,
            bondRateOverride: 0,
            aiWorkspaceSlug: null,
            venue: "Generic",
            quoteItems: [],
            includePricingBreakdown: false,
            showPricingTables: true,
            showIntroText: true,
            showBaseBidTable: false,
            showSpecifications: true,
            showCompanyFooter: true,
            showPaymentTerms: false,
            showSignatureBlock: false,
            showAssumptions: false,
            showExhibitA: false,
            showExhibitB: false,
            showNotes: true,
            showScopeOfWork: false,
            pageLayout: "portrait-letter",
            specsDisplayMode: "extended",
            tableHeaderOverrides: {},
            descriptionOverrides: {},
            priceOverrides: {},
            customProposalNotes: "",
            loiHeaderText: "",
            signatureBlockText: "",
            purchaserLegalName: "",
            includeResponsibilityMatrix: false,
            responsibilityMatrix: null,
            respMatrixFormatOverride: "auto",
            pricingMode: "STANDARD",
            masterTableIndex: null,
            status: "DRAFT",
            source: null,
            embeddingStatus: null,
        }
    };

    const mockReq = new NextRequest("http://localhost/api/proposals/generate", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(formPayload),
    });

    const pdfResponse = await generateProposalPdfServiceV2(mockReq);

    if (pdfResponse.status !== 200) {
      const errorBody = await pdfResponse.json().catch(() => ({}));
      return NextResponse.json({ error: typeof errorBody?.error === "string" ? errorBody.error : "PDF generation failed"}, { status: pdfResponse.status });
    }

    const bytes = await pdfResponse.arrayBuffer();
    if (bytes.byteLength === 0) {
      return NextResponse.json({ error: "Generated PDF is empty" }, { status: 500 });
    }

    const safeName = (estimate.name || estimate.projectName || "Twenty_Estimate").replace(/\s+/g, "_").replace(/[^\w\-_.]/g, "");
    
    return new Response(bytes, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safeName}.pdf"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err: any) {
    log.error("[twenty-bridge/export-proposal-pdf]", err?.message || err);
    return NextResponse.json(
      { error: "Twenty bridge PDF export failed", detail: String(err?.message || err).slice(0, 500) },
      { status: 500 }
    );
  }
}
