import { FORM_DEFAULT_VALUES } from "@/lib/variables";

/**
 * Map DB Proposal schema to Form schema (ProposalType-like shape)
 * DB stores flat structure; Form expects nested structure.
 */
export function mapDbProposalToFormSchema(dbProject: any) {
    const cfg = (dbProject.documentConfig || {}) as any;
    const documentMode = (dbProject.documentMode || "BUDGET") as "BUDGET" | "PROPOSAL" | "LOI" | "CONTRACT" | "CHANGE_ORDER";
    const documentType = (documentMode === "LOI" || documentMode === "CONTRACT" || documentMode === "CHANGE_ORDER") ? "LOI" : "First Round";
    const pricingType = (documentMode === "PROPOSAL" || documentMode === "CONTRACT" || documentMode === "CHANGE_ORDER") ? "Hard Quoted" : "Budget";
    const manualTableMode = cfg.manualTableMode ?? (
        dbProject.mirrorMode === false &&
        dbProject.calculationMode !== "ESTIMATE" &&
        !((dbProject.pricingDocument as any)?.tables?.length > 0)
    );

    return {
        sender: FORM_DEFAULT_VALUES.sender,
        receiver: {
            name: dbProject.clientName || "",
            address: dbProject.clientAddress || "",
            zipCode: dbProject.clientZip || "",
            city: dbProject.clientCity || "",
            country: "",
            email: "",
            phone: "",
            customInputs: [],
        },
        details: {
            proposalLogo: "",
            proposalId: dbProject.id,
            proposalName: dbProject.clientName,
            proposalNumber: dbProject.id.slice(-8).toUpperCase(),
            proposalDate: dbProject.createdAt ? new Date(dbProject.createdAt).toISOString().split("T")[0] : "",
            dueDate: "",
            items: [],
            currency: cfg.currency || (dbProject.pricingDocument as any)?.currency || "USD",
            exchangeRate: typeof cfg.exchangeRate === "number" && cfg.exchangeRate > 0 ? cfg.exchangeRate : 1,
            language: "English",
            taxDetails: { amount: 0, amountType: "amount", taxID: "" },
            discountDetails: { amount: 0, amountType: "amount" },
            shippingDetails: { cost: 0, costType: "amount" },
            paymentInformation: { bankName: "", accountName: "", accountNumber: "" },
            additionalNotes: dbProject.additionalNotes || "",
            paymentTerms: dbProject.paymentTerms || "50% on Deposit, 40% on Mobilization, 10% on Substantial Completion",
            substantialCompletionDate: dbProject.substantialCompletionDate || "",
            totalAmountInWords: "",
            documentType: documentType as any,
            pricingType: pricingType as any,
            documentMode: documentMode as any,
            pdfTemplate: 5,
            subTotal: 0,
            totalAmount: 0,
            overheadRate: Number(dbProject.overheadRate) || 0.10,
            profitRate: Number(dbProject.profitRate) || 0.05,
            screens: (dbProject.screens || []).map((s: any) => ({
                id: s.id,
                name: s.name || "Display",
                externalName: s.externalName || "",
                customDisplayName: s.customDisplayName || "",
                group: s.group || "",
                pitchMm: Number(s.pixelPitch) || 0,
                widthFt: Number(s.width) || 0,
                heightFt: Number(s.height) || 0,
                brightness: s.brightness != null ? Number(s.brightness) : "",
                hiddenFromSpecs: !!s.hiddenFromSpecs,
                quantity: s.quantity ?? 1,
                serviceType: s.serviceType || "",
                formFactor: s.formFactor || "",
                lineItems: (s.lineItems || []).map((li: any) => ({
                    category: li.category,
                    cost: Number(li.cost) || 0,
                    margin: Number(li.margin) || 0,
                    price: Number(li.price) || 0,
                })),
            })),
            internalAudit: dbProject.internalAudit ? JSON.parse(dbProject.internalAudit) : {},
            clientSummary: dbProject.clientSummary ? JSON.parse(dbProject.clientSummary) : {},
            mirrorMode: typeof dbProject.mirrorMode === "boolean"
                ? dbProject.mirrorMode
                : (dbProject.calculationMode === "MIRROR" || (dbProject.pricingDocument as any)?.tables?.length > 0 ? true : undefined),
            calculationMode: dbProject.calculationMode || "INTELLIGENCE",
            manualTableMode,
            taxRateOverride: Number(dbProject.taxRateOverride) || 0,
            bondRateOverride: Number(dbProject.bondRateOverride) || 0,
            aiWorkspaceSlug: dbProject.aiWorkspaceSlug || null,
            venue: (dbProject.venue || "Generic") as "Milan Puskar Stadium" | "WVU Coliseum" | "Generic",
            quoteItems: (dbProject.quoteItems || []) as any,
            includePricingBreakdown: cfg.includePricingBreakdown ?? false,
            showPricingTables: manualTableMode ? false : (cfg.showPricingTables ?? true),
            showIntroText: cfg.showIntroText ?? true,
            freeformTables: Array.isArray(cfg.freeformTables) ? cfg.freeformTables : [],
            showFreeformTables: cfg.showFreeformTables ?? true,
            // Service Contract / Service Proposal per-instance state. Like the
            // changeOrder* fields there are no dedicated columns — documentConfig
            // is the storage; without these reads every service field (purchaser,
            // venue, term, exhibit edits, imported fee table) died on reload.
            serviceContractTemplateId: cfg.serviceContractTemplateId ?? undefined,
            serviceContractProjectType: cfg.serviceContractProjectType ?? undefined,
            serviceContractPurchaserName: cfg.serviceContractPurchaserName ?? "",
            serviceContractVenueName: cfg.serviceContractVenueName ?? "",
            serviceContractPurchaserAddress: cfg.serviceContractPurchaserAddress ?? "",
            serviceContractAgreementDate: cfg.serviceContractAgreementDate ?? "",
            serviceContractTermStart: cfg.serviceContractTermStart ?? "",
            serviceContractTermEnd: cfg.serviceContractTermEnd ?? "",
            serviceContractSignatureText: cfg.serviceContractSignatureText ?? "",
            termExhibitOverrides: cfg.termExhibitOverrides ?? {},
            serviceProposalIntro: cfg.serviceProposalIntro ?? "",
            servicePricingDocument: cfg.servicePricingDocument ?? undefined,
            showBaseBidTable: cfg.showBaseBidTable ?? false,
            showSpecifications: manualTableMode ? false : (cfg.showSpecifications ?? true),
            showCompanyFooter: cfg.showCompanyFooter ?? true,
            showPaymentTerms: cfg.showPaymentTerms ?? false,
            showTermsAndConditions: cfg.showTermsAndConditions ?? documentMode === "CONTRACT",
            showSubstantialCompletionDate: cfg.showSubstantialCompletionDate ?? documentMode === "CONTRACT",
            showSignatureBlock: cfg.showSignatureBlock ?? false,
            showAssumptions: false,
            showExhibitA: cfg.showExhibitA ?? false,
            showExhibitB: cfg.showExhibitB ?? false,
            showNotes: cfg.showNotes ?? true,
            showScopeOfWork: manualTableMode ? false : (cfg.showScopeOfWork ?? false),
            pageLayout: cfg.pageLayout ?? "portrait-letter",
            specsDisplayMode: dbProject.specsDisplayMode || cfg.specsDisplayMode || "extended",
            tableHeaderOverrides: (dbProject as any).tableHeaderOverrides || {},
            descriptionOverrides: (dbProject as any).descriptionOverrides || {},
            priceOverrides: (dbProject as any).priceOverrides || {},
            customProposalNotes: dbProject.customProposalNotes || "",
            loiHeaderText: dbProject.loiHeaderText || "",
            signatureBlockText: dbProject.signatureBlockText || "",
            purchaserLegalName: dbProject.purchaserLegalName || "",
            includeResponsibilityMatrix: manualTableMode ? false : (dbProject.includeResponsibilityMatrix ?? false),
            showResponsibilityMatrix: manualTableMode ? false : (cfg.showResponsibilityMatrix ?? true),
            responsibilityMatrix: dbProject.responsibilityMatrix || null,
            respMatrixFormatOverride: dbProject.respMatrixFormatOverride || "auto",
            pricingDocument: dbProject.pricingDocument || undefined,
            parserValidationReport: dbProject.parserValidationReport || (dbProject.pricingDocument as any)?.metadata?.validation || undefined,
            sourceWorkbookHash: dbProject.sourceWorkbookHash || (dbProject.pricingDocument as any)?.metadata?.sourceWorkbookHash || undefined,
            parserStrictVersion: dbProject.parserStrictVersion || (dbProject.pricingDocument as any)?.metadata?.parserStrictVersion || undefined,
            pricingMode: dbProject.pricingMode || "STANDARD",
            masterTableIndex: dbProject.masterTableIndex ?? null,
            status: dbProject.status || "DRAFT",
            source: dbProject.source || null,
            embeddingStatus: dbProject.embeddingStatus || null,
            // Change Order fields (only meaningful when documentMode === "CHANGE_ORDER")
            changeOrderNumber: dbProject.changeOrderNumber || cfg.changeOrderNumber || "",
            changeOrderRequestedBy: dbProject.changeOrderRequestedBy || cfg.changeOrderRequestedBy || "",
            changeOrderDate: dbProject.changeOrderDate || cfg.changeOrderDate || "",
            changeOrderOriginalContractNumber: dbProject.changeOrderOriginalContractNumber || cfg.changeOrderOriginalContractNumber || "",
            changeOrderOriginalAgreementDate: cfg.changeOrderOriginalAgreementDate || "",
            changeOrderOriginalContractAmount: Number(dbProject.changeOrderOriginalContractAmount || cfg.changeOrderOriginalContractAmount) || 0,
            changeOrderPreviousTotalAmount: Number(cfg.changeOrderPreviousTotalAmount) || 0,
            changeOrderOverheadPct: Number(dbProject.changeOrderOverheadPct || cfg.changeOrderOverheadPct) || 0,
            changeOrderIntroText: dbProject.changeOrderIntroText || cfg.changeOrderIntroText || "",
            showChangeOrderTotals: cfg.showChangeOrderTotals ?? true,
        },
        marginAnalysis: dbProject.marginAnalysis || undefined,
    };
}
