/**
 * Scoping Workbook Importer
 *
 * Parses an uploaded scoping workbook Excel (previously generated by ANC)
 * and extracts updated costs, margins, and quantities.
 *
 * Reads from "LED Cost Sheet" and "Margin Analysis" sheets, matching
 * rows back to extracted specs by display name.
 */

import ExcelJS from "exceljs";
import type { ExtractedLEDSpec } from "@/services/rfp/unified/types";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ImportedDisplay {
  /** Index in the original specs array */
  specIndex: number;
  /** Display name (for matching verification) */
  displayName: string;
  /** Updated costs from the workbook */
  hardwareCost: number | null;
  processorCost: number | null;
  shippingCost: number | null;
  installCost: number | null;
  structuralCost: number | null;
  pmCost: number | null;
  engCost: number | null;
  /** Updated margin % (0-1 scale) */
  marginPct: number | null;
  /** Updated selling price */
  sellingPrice: number | null;
  /** Updated total cost */
  totalCost: number | null;
  /** Dimensions (if user edited them) */
  widthFt: number | null;
  heightFt: number | null;
  quantity: number | null;
  /** Per-sqft rate */
  ratePerSqFt: number | null;
  /** Whether this row had meaningful updated data */
  hasUpdates: boolean;
}

export interface ScopingImportResult {
  /** Parsed displays matched to spec indices */
  displays: ImportedDisplay[];
  /** Source file name */
  filename: string;
  /** How many specs had updates */
  updatedCount: number;
  /** How many specs had no match in the workbook */
  missingCount: number;
  /** Warnings (mismatches, parse errors) */
  warnings: string[];
  /** Summary of changes */
  summary: {
    totalCostBefore: number;
    totalCostAfter: number;
    costDelta: number;
  };
}

// ─── Importer ───────────────────────────────────────────────────────────────

export async function importScopingWorkbook(
  buffer: Buffer,
  originalSpecs: ExtractedLEDSpec[],
  filename: string,
): Promise<ScopingImportResult> {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);

  const warnings: string[] = [];
  const displays: ImportedDisplay[] = [];

  // Try "LED Cost Sheet" first (our generated format), then "Margin Analysis"
  const ledSheet = findSheet(workbook, ["LED Cost Sheet", "LED_Cost_Sheet", "LED Cost"]);
  const marginSheet = findSheet(workbook, ["Margin Analysis", "Margin-Analysis", "MarginAnalysis"]);

  if (!ledSheet && !marginSheet) {
    return {
      displays: [],
      filename,
      updatedCount: 0,
      missingCount: originalSpecs.length,
      warnings: ["No 'LED Cost Sheet' or 'Margin Analysis' sheet found in the workbook"],
      summary: { totalCostBefore: 0, totalCostAfter: 0, costDelta: 0 },
    };
  }

  // Prefer LED Cost Sheet (more columns), fall back to Margin Analysis
  if (ledSheet) {
    parseLedCostSheet(ledSheet, originalSpecs, displays, warnings);
  } else if (marginSheet) {
    parseMarginAnalysis(marginSheet, originalSpecs, displays, warnings);
  }

  // Check for missing specs
  const matchedIndices = new Set(displays.map((d) => d.specIndex));
  const missingSpecs = originalSpecs.filter((_, i) => !matchedIndices.has(i));
  if (missingSpecs.length > 0) {
    warnings.push(
      `Missing data for ${missingSpecs.length} display(s): ${missingSpecs.map((s) => s.name).join(", ")}`,
    );
  }

  const updatedCount = displays.filter((d) => d.hasUpdates).length;

  // Calculate cost deltas
  const totalCostAfter = displays.reduce((s, d) => s + (d.totalCost ?? 0), 0);

  return {
    displays,
    filename,
    updatedCount,
    missingCount: missingSpecs.length,
    warnings,
    summary: {
      totalCostBefore: 0, // Caller fills this from existing pricing state
      totalCostAfter,
      costDelta: 0,
    },
  };
}

// ─── LED Cost Sheet Parser ──────────────────────────────────────────────────

function parseLedCostSheet(
  sheet: ExcelJS.Worksheet,
  specs: ExtractedLEDSpec[],
  displays: ImportedDisplay[],
  warnings: string[],
) {
  // Find header row by looking for "Display" column
  const { headerRow, colMap } = findHeaders(sheet, [
    "display", "vendor", "product", "pitch",
    "h (ft)", "w (ft)", "h(ft)", "w(ft)", "height", "width",
    "qty", "quantity",
    "total sqft", "sqft",
    "$/sqft", "rate",
    "display cost", "hardware", "led cost",
    "processor", "shipping",
    "total cost",
    "margin %", "margin%",
    "selling price", "sell price", "sell",
    "install", "structural", "pm", "eng",
  ]);

  if (headerRow === 0) {
    warnings.push("LED Cost Sheet: Could not find header row");
    return;
  }

  // Map semantic column groups
  const nameCol = colMap["display"] ?? 0;
  const hCol = colMap["h (ft)"] ?? colMap["h(ft)"] ?? colMap["height"] ?? 0;
  const wCol = colMap["w (ft)"] ?? colMap["w(ft)"] ?? colMap["width"] ?? 0;
  const qtyCol = colMap["qty"] ?? colMap["quantity"] ?? 0;
  const rateCol = colMap["$/sqft"] ?? colMap["rate"] ?? 0;
  const hwCostCol = colMap["display cost"] ?? colMap["hardware"] ?? colMap["led cost"] ?? 0;
  const procCol = colMap["processor"] ?? 0;
  const shipCol = colMap["shipping"] ?? 0;
  const totalCostCol = colMap["total cost"] ?? 0;
  const marginCol = colMap["margin %"] ?? colMap["margin%"] ?? 0;
  const sellCol = colMap["selling price"] ?? colMap["sell price"] ?? colMap["sell"] ?? 0;
  const installCol = colMap["install"] ?? 0;
  const structCol = colMap["structural"] ?? 0;
  const pmCol = colMap["pm"] ?? 0;
  const engCol = colMap["eng"] ?? 0;

  // Parse data rows
  for (let rowIdx = headerRow + 1; rowIdx <= sheet.rowCount; rowIdx++) {
    const row = sheet.getRow(rowIdx);
    const rawName = String(row.getCell(nameCol).value || "").trim();

    // Skip empty, total, instruction rows
    if (!rawName || rawName === "—" || rawName === "") continue;
    if (rawName.toLowerCase().startsWith("total")) break;
    if (rawName.startsWith("+")) continue; // "Add Screen" row

    // Match to spec by name (fuzzy)
    const specIndex = matchSpecByName(rawName, specs);
    if (specIndex < 0) {
      warnings.push(`Row ${rowIdx}: Could not match "${rawName}" to any extracted spec`);
      continue;
    }

    const imported: ImportedDisplay = {
      specIndex,
      displayName: rawName,
      hardwareCost: hwCostCol ? parseNum(row.getCell(hwCostCol).value) : null,
      processorCost: procCol ? parseNum(row.getCell(procCol).value) : null,
      shippingCost: shipCol ? parseNum(row.getCell(shipCol).value) : null,
      installCost: installCol ? parseNum(row.getCell(installCol).value) : null,
      structuralCost: structCol ? parseNum(row.getCell(structCol).value) : null,
      pmCost: pmCol ? parseNum(row.getCell(pmCol).value) : null,
      engCost: engCol ? parseNum(row.getCell(engCol).value) : null,
      marginPct: marginCol ? parseNum(row.getCell(marginCol).value) : null,
      sellingPrice: sellCol ? parseNum(row.getCell(sellCol).value) : null,
      totalCost: totalCostCol ? parseNum(row.getCell(totalCostCol).value) : null,
      widthFt: wCol ? parseNum(row.getCell(wCol).value) : null,
      heightFt: hCol ? parseNum(row.getCell(hCol).value) : null,
      quantity: qtyCol ? parseNum(row.getCell(qtyCol).value) : null,
      ratePerSqFt: rateCol ? parseNum(row.getCell(rateCol).value) : null,
      hasUpdates: false,
    };

    // Check if any meaningful data was imported
    imported.hasUpdates = (
      imported.hardwareCost != null ||
      imported.totalCost != null ||
      imported.marginPct != null ||
      imported.sellingPrice != null
    );

    displays.push(imported);
  }
}

// ─── Margin Analysis Parser ─────────────────────────────────────────────────

function parseMarginAnalysis(
  sheet: ExcelJS.Worksheet,
  specs: ExtractedLEDSpec[],
  displays: ImportedDisplay[],
  warnings: string[],
) {
  // Margin Analysis has: [empty] | Zone / Line Item | Cost | Selling Price | Margin $ | Margin %
  const { headerRow, colMap } = findHeaders(sheet, [
    "zone", "line item", "zone / line item",
    "cost", "selling price", "sell",
    "margin $", "margin%", "margin %",
  ]);

  if (headerRow === 0) {
    warnings.push("Margin Analysis: Could not find header row");
    return;
  }

  const nameCol = colMap["zone / line item"] ?? colMap["zone"] ?? colMap["line item"] ?? 2;
  const costCol = colMap["cost"] ?? 0;
  const sellCol = colMap["selling price"] ?? colMap["sell"] ?? 0;
  const marginPctCol = colMap["margin %"] ?? colMap["margin%"] ?? 0;

  for (let rowIdx = headerRow + 1; rowIdx <= sheet.rowCount; rowIdx++) {
    const row = sheet.getRow(rowIdx);
    const rawName = String(row.getCell(nameCol).value || "").trim();

    // Skip empty, sub-detail (indented), total rows
    if (!rawName || rawName === "" || rawName === "—") continue;
    if (rawName.startsWith("    ") || rawName.startsWith("\t")) continue; // sub-line detail
    if (rawName.toUpperCase().startsWith("SUBTOTAL") || rawName.toUpperCase().startsWith("GRAND TOTAL")) break;
    if (rawName.toUpperCase() === "TAX" || rawName.toUpperCase() === "BOND") continue;

    const specIndex = matchSpecByName(rawName, specs);
    if (specIndex < 0) continue; // Could be a service category row, skip silently

    const cost = costCol ? parseNum(row.getCell(costCol).value) : null;
    const sell = sellCol ? parseNum(row.getCell(sellCol).value) : null;
    const marginPct = marginPctCol ? parseNum(row.getCell(marginPctCol).value) : null;

    displays.push({
      specIndex,
      displayName: rawName,
      hardwareCost: null, // Not broken out in Margin Analysis
      processorCost: null,
      shippingCost: null,
      installCost: null,
      structuralCost: null,
      pmCost: null,
      engCost: null,
      marginPct,
      sellingPrice: sell,
      totalCost: cost,
      widthFt: null,
      heightFt: null,
      quantity: null,
      ratePerSqFt: null,
      hasUpdates: cost != null || sell != null || marginPct != null,
    });
  }
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function findSheet(workbook: ExcelJS.Workbook, names: string[]): ExcelJS.Worksheet | null {
  for (const name of names) {
    const sheet = workbook.worksheets.find(
      (ws) => ws.name.toLowerCase().replace(/[\s_-]/g, "") === name.toLowerCase().replace(/[\s_-]/g, ""),
    );
    if (sheet) return sheet;
  }
  return null;
}

function findHeaders(
  sheet: ExcelJS.Worksheet,
  targetColumns: string[],
): { headerRow: number; colMap: Record<string, number> } {
  let headerRow = 0;
  const colMap: Record<string, number> = {};

  sheet.eachRow((row, rowNumber) => {
    if (headerRow > 0) return;

    const cellValues: string[] = [];
    row.eachCell((cell) => {
      cellValues.push(String(cell.value || "").toLowerCase().trim());
    });

    const joined = cellValues.join(" ");
    // Header row must contain "display" or "zone" or "line item"
    if (joined.includes("display") || joined.includes("zone") || joined.includes("line item")) {
      headerRow = rowNumber;
      row.eachCell((cell, colNumber) => {
        const val = String(cell.value || "").toLowerCase().trim();
        // Match against target column names
        for (const target of targetColumns) {
          if (val === target || val.includes(target)) {
            colMap[target] = colNumber;
          }
        }
      });
    }
  });

  return { headerRow, colMap };
}

function matchSpecByName(rawName: string, specs: ExtractedLEDSpec[]): number {
  const clean = rawName.toLowerCase().replace(/\s+/g, " ").trim();

  // Exact match
  let idx = specs.findIndex((s) => s.name.toLowerCase().trim() === clean);
  if (idx >= 0) return idx;

  // Partial match — spec name contained in raw name (handles "name — location" format)
  idx = specs.findIndex((s) => clean.includes(s.name.toLowerCase().trim()));
  if (idx >= 0) return idx;

  // Reverse partial — raw name contained in spec name
  idx = specs.findIndex((s) => s.name.toLowerCase().trim().includes(clean));
  if (idx >= 0) return idx;

  return -1;
}

function parseNum(value: unknown): number | null {
  if (value == null) return null;
  if (typeof value === "number") return value;
  if (typeof value === "string") {
    const cleaned = value.replace(/[$,€£\s%]/g, "");
    const num = parseFloat(cleaned);
    return isNaN(num) ? null : num;
  }
  // ExcelJS formula cells: { formula: string, result: number }
  if (typeof value === "object" && "result" in (value as Record<string, unknown>)) {
    return parseNum((value as Record<string, unknown>).result);
  }
  return null;
}
