/**
 * Graphics Production terms exhibit — VERBATIM from ANC's Ad Hoc Graphics
 * Quotation template (docs/service-agreements/TEMPLATE_Ad Hoc Graphics Quotation.docx).
 * Uses 'Purchaser' throughout — no party-name placeholder needed.
 * Do NOT rewrite or paraphrase. Editable per-instance via termExhibitOverrides.
 */
export const GRAPHICS_PRODUCTION_BODY = `TERMS & CONDITIONS FOR GRAPHICS PRODUCTION
Scope of Services.
ANC will create graphics to be displayed on LED displays (“Contract Graphics”) during the Term. The Purchaser will have the right to create an specified amount of Contract Graphics as defined in the Scope of Work, including statistical layouts, sponsor animations, Purchaser animations, player headshots, and game prompts for Home Games, subject to ANC’s commercially reasonable staffing and production capabilities.
Notwithstanding the foregoing, Contract Graphics will include, but are not limited to, two-dimensional and three-dimensional game prompt, Purchaser and building identified graphics and sponsor graphics which do not exceed thirty (30) seconds in length. Player headshots for the Purchaser’s players and the players of visiting universities will be created by ANC if proper headshots in formats acceptable to ANC are delivered by Purchaser to ANC on a timely basis. Editing of live video is not part of the services being offered as part of ANC’s graphics services; provided, however, that ANC can utilize video clips in Contract Graphics if the edited video clips are supplied by Purchaser. In addition, Contract Graphics will not include three-dimensional interactive games, video opens, or animations with character animation (collectively, “Excluded Services”). For purposes of this Agreement, “character animation” means the custom creation of animated characters involving elements that include a sense of realism, personality, and emotion.
Purchaser will provide written direction and/or creative concepts to ANC before ANC begins to create the applicable Contract Graphics. ANC will produce Contract Graphics and submit a proof to Purchaser within five (5) business days after ANC receives approval of the creative concept by Purchaser, unless a different production schedule is agreed to between the parties. Depending on the complexity of the Contract Graphics, revisions can take from two (2) to five (5) business days to process. For Contract Graphics with a high level of complexity, ANC will work with Purchaser to determine a mutually agreeable timeline for delivery. ANC will use its best efforts to accommodate requests for expedited production of Contract Graphics.
ANC shall assign Purchaser a client services account executive to (1) create a password protected directory for the Purchaser within the “Workspace” portion of ANC’s website which shall contain an artwork section for electronic submission and approval of artwork and (2) coordinate all graphic production and quality control procedures among Purchaser and its advertisers, and all graphics producers so as to ensure the timely and correct display of advertiser’s advertising on the LED Display. Prior to the final production of Contract Graphics, Purchaser and their advertisers may view proposed artwork for the Contract Graphics via the Workspace portion of ANC’s website. Contract Graphics will be stored on ANC’s secure server during the Service Period and may be accessed during that time by Purchaser, ideally through a high-speed web connection. Any content created and supplied by Purchaser and/or its advertisers for display will only be trafficked via ANC’s FTP site.
ANC will only supply Purchaser with final completed Contract Graphics, in the form of uncompressed .AVI or .MOV files, which can be displayed on the LED System. Such files will be trafficked only via ANC’s FTP site. ANC is not responsible for supplying original project files used in the creation of the graphics.
Excluded Services may be provided by ANC at Purchaser’s request and will be subject to additional charges in accordance with ANC’s rate card then in effect for such services.
Ownership of Materials.
All Purchaser trademarks, trade names, service marks, brand logos, label designs and artwork or materials delivered by Purchaser to ANC (hereinafter collectively referred to as “Purchaser Works”) shall be and remain the property of Purchaser. Any and all rights under trademark or copyright law or other property rights with respect to such Purchaser Works shall inure to the benefit of and remain the exclusive property of Purchaser.
All Contract Graphics prepared by ANC upon download by Purchaser shall become Purchaser’s copyrighted property. It is understood that there may be limitations on the use and ownership of Contract Graphics by virtue of the preexisting rights of ANC or third parties. Whenever possible, ANC shall advise Purchaser of the existence of such limitations. Purchaser acknowledges that to the extent Contract Graphics are created based on underlying preexisting works already owned by ANC, such Contract Graphics are derivative works and Purchaser will have no claim of ownership to such underlying works. Purchaser’s ownership rights shall only extend to the derivative aspect of such works, namely the portion that is created for Purchaser specifically. ANC agrees to give Purchaser or any person designated by Purchaser any reasonable assistance required to perfect the rights defined in this paragraph. The covenants made in this paragraph shall survive the termination of this agreement.
At termination of this agreement, Purchaser agrees that any plans, ideas, graphics or animations prepared by ANC and submitted to Purchaser (whether submitted separately or in conjunction with or as part of other material) but rejected and not downloaded, shall remain ANC’s property unless it was either mutually agreed in writing that any such plan or idea became Purchaser’s property, or specific payment of the cost of its development was agreed upon and made by Purchaser. Purchaser agrees to return to ANC any copy, artwork, plates or other physical embodiment of the creative work relating to any such ideas or plans, which may be in Purchaser’s possession upon termination.
Upon payment to ANC and transfer of ownership of Contract Graphics to Purchaser, Purchaser grants ANC the right to display the Contract Graphics in ANC’s animation portfolio, whether on-line or off-line, and in any recorded format, under technology currently known or to be known in the future. Such right of display shall be unlimited in duration.
Warranties.
ANC warrants and represents to Purchaser that (i) it will perform its graphics production services hereunder with care, skill and diligence, consistent with or above applicable professional standards; (ii) its performance under this Agreement will comply with all federal, state and local laws and regulations applicable to this Agreement; and (iii) except for the limitations disclosed in writing to Purchaser pursuant to Section 5(b) above, the Contract Graphics do not infringe the copyright or similar intellectual property rights of any third party nor incorporate trade secrets or other proprietary information of a third party.
Purchaser warrants (i) the accuracy of any and all information and Purchaser Works it provides to ANC pursuant to this Agreement and (ii) that its performance under this Agreement will comply with all federal, state and local laws and regulations applicable to this Agreement as well as the fact that such information and Purchaser Works do not infringe the copyright or similar rights of any third party nor incorporate trade secrets or other proprietary information of a third party. Furthermore, Purchaser warrants that before implementing any of the materials provided by ANC, Purchaser will do its own legal clearance of such materials to be certain they are implemented in full compliance with the law.
INDEMNITIES.
ANC shall indemnify, defend and hold harmless Purchaser, as well as its agents, members and employees, with respect to any third party claims, demand, cause of action, debt cost, loss, damage, expense or liability, including reasonable attorneys’ fees, arising from or based on (i) any breach by ANC of the foregoing warranties, (ii) Purchaser’s use of material furnished by ANC, or (iii) any intentional or willful conduct or negligence of any of ANC employees or agents.
Purchaser shall indemnify, defend and hold harmless ANC, its agents and employees, with respect to any third party claims, demand, cause of action, debt cost, loss, damage, expense or liability, including reasonable attorneys’ fees, arising from or based on (i) any breach by Purchaser of the foregoing warranties, (ii) actions instituted by third parties which result from the use by ANC of material furnished by Purchaser or any third party on Purchaser’s behalf or where material created by ANC is substantially changed by Purchaser, or (iii) any intentional or willful conduct or negligence of any of Purchaser’s employees or agents other than ANC.`;
