/**
 * Software End User License Agreement exhibit — VERBATIM from ANC's Hub City
 * Spartanburgers VSB + LiveSync License 2026 (Exhibit B) —
 * docs/service-agreements/Hub City Spartanburgers_VSB and LiveSync License 2026.docx.
 * Uses 'Licensee'/'Licensor' as defined terms throughout; only the preamble
 * carries the specific licensee name+address, templatized to {{purchaserName}}/
 * {{purchaserAddress}} (substituted at render time). Do NOT rewrite or paraphrase.
 */
export const SOFTWARE_EULA_BODY = `Software End User License Agreement
This Software End User License Agreement (“Agreement”) is a binding agreement between ANC Sports Enterprises, LLC, a Delaware limited liability company located at 2 Manhattanville Road, Suite 402, Purchase, New York 10577, Tel: (914) 696-2100 (“Licensor”) and {{purchaserName}}, located at {{purchaserAddress}} (“Licensee”), and is effective as of the latest date of signature of the parties hereto (“Effective Date”). ANC and Licensee are at times collectively referred to in this Agreement as “the parties” and separately as a “party.”
LICENSOR PROVIDES THE SOFTWARE SOLELY ON THE TERMS AND CONDITIONS SET FORTH IN THIS AGREEMENT AND ON THE CONDITION THAT LICENSEE ACCEPTS AND COMPLIES WITH THEM.  BY SIGNING THIS AGREEMENT YOU (A) ACCEPT THIS AGREEMENT AND AGREE THAT LICENSEE IS LEGALLY BOUND BY ITS TERMS AND CONDITIONS; AND (B) REPRESENT AND WARRANT THAT: (I) IF YOU ARE AN INDIVIDUAL, YOU ARE 18 YEARS OF AGE OR OLDER OR OF LEGAL AGE TO SIGN AND ENTER INTO THIS AGREEMENT; AND (II) IF LICENSEE IS A CORPORATION, GOVERNMENTAL ORGANIZATION, OR OTHER LEGAL ENTITY, YOU HAVE THE RIGHT, POWER, AND AUTHORITY TO ENTER INTO THIS AGREEMENT ON BEHALF OF LICENSEE AND BIND LICENSEE TO ITS TERMS AND CONDITIONS.  IF LICENSEE DOES NOT AGREE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT, LICENSOR WILL NOT AND DOES NOT LICENSE THE SOFTWARE TO LICENSEE. YOU MUST NOT DOWNLOAD, INSTALL, USE OR ACCESS THE SOFTWARE OR DOCUMENTATION AND THIS AGREEMENT SHALL NOT BE BINDING UPON LICENSOR.
NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT OR YOUR OR LICENSEE’S ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, NO LICENSE OTHER THAN AS SET FORTH IN THIS AGREEMENT IS GRANTED (WHETHER EXPRESSLY, BY IMPLICATION, OR OTHERWISE) UNDER THIS AGREEMENT, AND THIS AGREEMENT EXPRESSLY EXCLUDES ANY RIGHT, CONCERNING ANY SOFTWARE THAT LICENSEE DID NOT ACQUIRE LAWFULLY OR THAT IS NOT A LEGITIMATE, AUTHORIZED COPY OF LICENSOR’S SOFTWARE.
Definitions.  In addition to any other terms defined in this Agreement, the following terms shall have the following meanings:
“Approved Hardware” means hardware or other equipment approved by Licensor and sold to Licensee by Licensor, which hardware or equipment can be used in conjunction or combination with the Software.
"Authorized Users" means the employees of Licensee authorized to use the Software pursuant to the license granted under this Agreement.
"Confidential Information" has the meaning set forth in Section 14.
"Documentation" means any and all manuals, instructions, specifications and other documents and materials in any form or media that Licensor generally makes available to licensees, or other end users of its Software and that describe Licensor’s Software’s operation, use, support, maintenance or other features.
“Effective Date” means the date as defined in the preamble.
“Excluded Use” means, unless otherwise agreed to in writing by Licensor, any use of the Software in connection with sports or entertainment related venues.
"Intellectual Property Rights" means any and all registered and unregistered rights granted, applied for or otherwise now or hereafter in existence under or related to any patent, patent application, copyright, trademark, service mark, trade dress, trade secret, database protection or other intellectual property rights laws, and all similar or equivalent rights or forms of protection, in any part of the world.
"Licensee" has the meaning set forth in the preamble.
"License Fees" means the license fees, including all taxes thereon, paid or required to be paid, by Licensee to Licensor for the license granted under this Agreement.
"Licensor" has the meaning set forth in the preamble.
"Sales Agreement" means any agreement entered into between Licensor and Licensee, for Licensee’s purchase of the license for the Software granted under this Agreement.
"Person" means an individual, corporation, partnership, joint venture, limited liability company, governmental authority, unincorporated organization, trust, association, or other entity.
"Personal Information" means any information that, individually or in combination with other information, does or can identify a specific individual or by or from which a specific individual may be identified, contacted or located.  Personal Information includes, but is not limited to the following types of information, personal first or last name(s), email addresses, phone numbers, social media handles or accounts, and home or business addresses.
“Social Media Posts” means any information or data submitted by a Third Party to a social media outlet or platform that is capable of then being displayed using the Software or Approved Hardware.
"Software" means the Licensor software product called VisionStats Baseball and LiveSync, in object code form, including any Documentation included in, or provided for use with, such software, including all Updates and any new version of the same.
"Term" has the meaning set forth in Section 10.
“Venue” means the physical location where the Software will be used as agreed between Licensor and Licensee, which location shall not be outside the United States of America and its territories and possessions, unless approved by Licensor in advance in writing.
"Third Party" means any Person other than Licensee or Licensor.
"Update" has the meaning set forth in Section 6(d).
License Grant and Scope.  Subject to and conditioned upon Licensee’s payment of the License Fees and Licensee’s strict compliance with all the terms and conditions set forth in this Agreement, Licensor hereby grants to Licensee a non-exclusive, non-transferable, non-sublicensable limited license during the Term to use in the Venue, solely by and through its Authorized Users, the Software and Documentation, solely as set forth in this Section 2 and subject to all conditions and limitations set forth in Section 3 or elsewhere in this Agreement.  This license grants Licensee the right, exercisable solely by and through Licensee’s Authorized Users, to:
Download, copy, and install in accordance with the Documentation one (1) copy of the Software on Approved Hardware owned or leased, and controlled by, Licensee.  In addition to the foregoing, Licensee has the right to make one copy of the Software solely for archival purposes and one copy of the Software solely for backup purposes, provided that Licensee shall not, and shall not allow any Person to, install or use any such copy other than if and for so long as any copy installed in accordance with the preceding sentence is inoperable and, provided, further, that Licensee uninstalls and otherwise deletes such inoperable copy(ies).  All copies of the Software made by the Licensee:
will be and shall remain the exclusive property of the Licensor;
will be subject to the terms and conditions of this Agreement; and
must include all trademark, copyright, patent, and other Intellectual Property Rights  notices contained in the original.
Use and run the Software as properly installed on Approved Hardware in accordance with this Agreement and the Documentation, solely as set forth in the Documentation and solely for Licensee’s business purposes, which purposes shall not include any Excluded Uses.  The use licensed under this Agreement is use permitted only on the Approved Hardware on which the Software is installed, at the physical location thereof and not via any remote access or other network.
Download or otherwise make a reasonable number of copies of the Documentation and use such Documentation, solely in support of its licensed use of the Software in accordance with this Agreement.  All copies of the Documentation made by Licensee:
will be and shall remain the exclusive property of the Licensor;
will be subject to the terms and conditions of this Agreement; and
must include all trademark, copyright, patent, and other Intellectual Property Rights notices contained in the original.
Transfer any copy of the Software from one computer to another, provided that:
the number of computers on which the Software is installed at any one time does not exceed the number permitted under Section 2(a).
Use Restrictions.  Licensee shall not, and shall require its Authorized Users not to, directly or indirectly:
use (including make any copies of) the Software or Documentation beyond the scope of the license granted under Section 2;
provide any other Person, including any subcontractor, independent contractor, affiliate, or service provider of Licensee, with access to or use of the Software or Documentation;
modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Software or Documentation or any part thereof;
combine the Software or any part thereof with, or incorporate the Software or any part thereof in, any other software or computer programs;
reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Software or any part thereof;
remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices provided on or with the Software or Documentation, including any copy thereof;
except as expressly set forth in Section 2(a) and Section 2(c), copy the Software or Documentation, in whole or in part;
rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Software, or any features or functionality of the Software, to any Third Party for any reason, whether or not over a network or on a hosted basis, including in connection with the Internet or any web hosting, wide area network (WAN), virtual private network (VPN), virtualization, time-sharing, service bureau, software-as-a-service (SaaS), cloud, or other technology or service;
use the Software or Documentation in violation of any law, regulation, or rule; or
use the Software or Documentation for purposes of competitive analysis of the Software, the development of a competing software product or service, or any other purpose that is to the Licensor's commercial disadvantage.
Responsibility for Use of Software.  Licensee is responsible and liable for all uses of the Software and Documentation through access thereto provided by Licensee, directly or indirectly.  Specifically, and without limiting the generality of the foregoing, Licensee is responsible and liable for all actions and failures to take required actions with respect to the Software and Documentation by its Authorized Users or by any other Person to whom Licensee or an Authorized User may provide access to or use of the Software and/or Documentation, whether such access or use is permitted by or in violation of this Agreement.
Compliance Measures.
The Software may contain technological copy protection or other security features designed to prevent unauthorized use of the Software, including features to protect against any use of the Software that is prohibited under Section 3.  Licensee shall not, and shall not attempt to, remove, disable, circumvent, or otherwise create or implement any workaround to, any such copy protection or security features.
On Licensor’s written request, Licensee shall conduct a review of its and its Authorized Users use of the Software and certify to Licensor in a written instrument signed by an officer of Licensee that it is in full compliance with this Agreement or, if Licensee discovers any noncompliance:
Licensee shall immediately remedy such noncompliance and provide Licensor with written notice thereof.  Licensee shall provide Licensor with all access and assistance as Licensor requests to further evaluate and remedy such noncompliance.
If Licensee’s use of the Software exceeds the number of copies or Authorized Users permitted under the license, Licensor shall have the remedies set forth in Section 5(d).]
During the Term, Licensor may, in Licensor's sole discretion, audit Licensee's use of the Software to ensure Licensee's compliance with this Agreement, provided that (i) any such audit shall be conducted on not less than three (3) days’ prior notice to Licensee, and (ii) no more than one (1) audit may be conducted in any six (6) month period except for good cause shown.  Licensor also may, in its sole discretion, audit Licensee's systems within six (6) months after the end of the Term to ensure Licensee has ceased use of the Software and removed all copies of the Software from such systems as required by this Agreement.  The Licensee shall fully cooperate with Licensor's personnel conducting such audits and provide all reasonable access requested by the Licensor to records, systems, equipment, information, and personnel, including machine IDs, serial numbers, and related information.  Licensor shall only examine information directly related to the Licensee's use of the Software.  Licensor may conduct audits only during Licensee’s normal business hours and in a manner that does not unreasonably interfere with the Licensee’s business operations.
If the audit or any of the measures taken or implemented under this Section 5 determines that the Licensee's use of the Software exceeds or exceeded the use permitted by this Agreement then:
Licensee shall, within three (3) days following the date of Licensor's written notification thereof, pay to Licensor the retroactive License Fees for such excess use and, unless Licensor terminates this Agreement pursuant its terms, obtain and pay for a valid license to bring Licensee's use into compliance with this Agreement.  In determining the Licensee Fee payable pursuant to the foregoing, (x) unless Licensee can demonstrate otherwise by documentary evidence, all excess use of the Software shall be deemed to have commenced on the commencement date of this Agreement or, if later, the completion date of any audit previously conducted by Licensor hereunder, and continued uninterrupted thereafter, and (y) the rates for such licenses shall be determined without regard to any discount to which Licensee may have been entitled had such use been properly licensed prior to its commencement (or deemed commencement).
Licensor's remedies set forth in this Section 5(d) are cumulative and are in addition to, and not in lieu of, all other remedies the Licensor may have at law or in equity, whether under this Agreement or otherwise.
Maintenance and Support.
During the Term of this Agreement, Licensee shall contact Licensor for all maintenance and support in connection with Licensee’s use of the Software, which maintenance and support shall be charged at fees determined by Licensor.
During the first year of the Term, Licensee shall be required to purchase maintenance services from Licensor, unless such services are provided under the Sales Agreement.
Unless otherwise specified in the Sales Agreement, Licensee shall have the option to continue to purchase further maintenance and technical support services directly from Licensor at prices determined by Licensor at Licensor’s sole discretion.
Maintenance and support services will include provision of such updates, upgrades, bug fixes, patches, and other error corrections (collectively, "Updates") as Licensor makes available to Licensee.  Licensor may develop and provide Updates in its sole discretion, and Licensee agrees that Licensor has no obligation to develop any Updates at all or for particular issues.  Licensee further agrees that all Updates will be deemed Software, and related documentation will be deemed Documentation, all subject to all terms and conditions of this Agreement.  Licensee acknowledges that Licensor may provide some or all Updates via download from a website designated by Licensor and that Licensee’s receipt thereof will require an Internet connection, which connection is Licensee’s sole responsibility.  Licensor has no obligation to provide Updates via any other media.  Maintenance and support services do not include any new version or new release of the Software that Licensor may issue as a separate or new product, and Licensor may determine whether any issuance qualifies as a new version, new release, or Update in its sole discretion.  In the event that Licensor determines that any issuance or release of the Software is a new version or new release, Licensor may require Licensee to execute a new End User License Agreement.
Licensor has no obligation to provide maintenance and support services, including Updates:
for any but the most current or immediately preceding version or release of the Software, as determined by Licensor in its discretion;
for any copy of Software for which all previously issued Updates have not been installed;
if Licensee is in breach under this Agreement; or
for any Software that has been modified other than by or with the authorization of Licensor, or that is being used with any hardware, software, configuration, or operating system not specified in the Documentation or expressly authorized by Licensor in writing.
Collection and Use of Data and Information.
Licensee acknowledges that Licensor may, directly or indirectly through the services of Third Parties, collect and store information regarding use of the Software, log files of data entered into the Software by Licensee or other Third Parties, including Social Media Posts, and about equipment on which the Software is installed or through which it is otherwise accessed and used.
Licensee agrees that the Licensor may use such information for any purpose related to any use of the Software by Licensee or on Licensee's equipment, including but not limited to:
improving the performance of the Software or developing Updates; and
verifying Licensee's compliance with the terms of this Agreement and enforcing the Licensor’s rights, including all Intellectual Property Rights in and to the Software.
Licensor shall keep logs of Social Media Posts, for a period of time as determined by Licensor in its sole discretion, which may be stored by Licensor for Licensee’s use thereof to verify dates and times of such Social Media Posts.  For Licensee’s use thereof, Licensor shall make such logs of Social Media Posts available to Licensee upon Licensee’s reasonable request.
Licensee acknowledges and agrees that, notwithstanding Licensor’s storage of data or other information concerning use of the Software, including Social Media Posts, Licensee shall be responsible for advising and informing any Third Parties who may submit through the Software data or information, including but not limited to, Social Media Posts or Personal Information, that such data or information may be stored and viewed by Licensee, Licensor, or other Third Parties.  Licensee shall also be responsible for providing notice to any minors or other individuals who are not the age of majority that any data or information they submit through the Software, including Social Media Posts or Personal Information, may be viewed by Third Parties.
Intellectual Property Rights.  Licensee acknowledges and agrees that the Software and Documentation are provided under license, and not sold, to Licensee.  Licensee does not acquire any ownership interest in the Software or Documentation under this Agreement, or any other rights thereto, other than to use the same in accordance with the license granted and subject to all terms, conditions, and restrictions under this Agreement.  Licensor and its licensors and service providers reserve and shall retain their entire right, title, and interest in and to the Software and all Intellectual Property Rights arising out of or relating to the Software, except as expressly granted to the Licensee in this Agreement.  Licensee shall use commercially reasonable efforts to safeguard all Software (including all copies thereof) from infringement, misappropriation, theft, misuse, or unauthorized access.  Licensee shall promptly notify Licensor if Licensee becomes aware of any infringement of the Licensor’s Intellectual Property Rights in the Software and fully cooperate with Licensor, at Licensor’s sole expense, in any legal action taken by Licensor to enforce its Intellectual Property Rights.
PAYMENT.  All License Fees shall be set by Licensor and payable to Licensor as determined by Licensor.  Non-payment of License Fees by Licensee may result in termination of this Agreement by Licensor.
Term and Termination.
This Agreement and the license granted hereunder shall remain in effect for the term set forth on the Sales Agreement or until earlier terminated as set forth herein (the “Term”).
Subject to payment of all License Fees due and owing, Licensee may terminate this Agreement by notifying Licensor at least 10 days prior to the intended date of termination and by ceasing to use and destroying all copies of the Software and Documentation.
Licensor may terminate this Agreement, effective upon written notice to Licensee, if Licensee, breaches this Agreement and such breach: (i) is incapable of cure; or (ii) being capable of cure, remains uncured for thirty (30) days after Licensor provides written notice thereof.
Licensor may terminate this Agreement, effective immediately, if Licensee files, or has filed against it, a petition for voluntary or involuntary bankruptcy or pursuant to any other insolvency law, makes or seeks to make a general assignment for the benefit of its creditors or applies for, or consents to, the appointment of a trustee, receiver, or custodian for a substantial part of its property.
Upon expiration or earlier termination of this Agreement, the license granted hereunder shall also terminate, and Licensee shall cease using and destroy all copies of the Software and Documentation. No expiration or termination shall affect Licensee's obligation to pay all Licensee Fees and any other fees for maintenance or support that may have become due before such expiration or termination, or entitle Licensee to any refund, in each case except as set forth in Section 11(c)(ii).
Limited Warranties, Exclusive Remedy, and Disclaimer/Warranty Disclaimer.
Solely with respect to Software for which Licensee has paid a License Fee, Licensor warrants that, for a period of thirty (30) days following the license date set forth on the Sales Agreement:
the Software will substantially contain the functionality described in the Documentation, and when properly installed on Approved Hardware, and operated in accordance with, the Documentation, will substantially perform in accordance therewith.
THE FOREGOING WARRANTIES DO NOT APPLY, AND LICENSOR STRICTLY DISCLAIMS ALL WARRANTIES, WITH RESPECT TO ANY THIRD-PARTY MATERIALS.
The warranties set forth in Section 11(a)(i) will not apply and will become null and void if Licensee breaches any material provision of this Agreement, or if Licensee, any Authorized User, or any other Person provided access to the Software by Licensee or any Authorized User, whether or not in violation of this Agreement:
installs or uses the Software on or in connection with any hardware or software not specified in the Documentation or approved or authorized by Licensor;
modifies or damages the Software, or the media on which it is provided, including abnormal physical or electrical stress; or
misuses the Software, including any use of the Software other than as specified in the Documentation or expressly authorized by Licensor in writing.
If, during the period specified in Section 11(a), any Software covered by the warranty set forth in such Section fails to perform substantially in accordance with the Documentation, and such failure is not excluded from warranty pursuant to Section 11(b), Licensor will, subject to promptly receiving notice in writing from Licensee of such failure, at its sole option, either:
repair or replace the Software, provided that Licensee provides Licensor with all information Licensor requests to resolve the reported failure, including sufficient information to enable the Licensor to recreate such failure; or
refund the License Fees paid for such Software, subject to Licensee’s ceasing all use of and, if requested by Licensor, returning to Licensor all copies of the Software.
If Licensor repairs or replaces the Software, the warranty will continue to run from the initial date specified on the Sales Agreement, and not from Licensee's receipt of the repair or replacement.  The remedies set forth in this Section 11(c) are Licensee’s sole remedies and Licensor’s sole liability under this Agreement.
EXCEPT FOR THE LIMITED WARRANTY SET FORTH IN SECTION 11(a), THE SOFTWARE AND DOCUMENTATION ARE PROVIDED TO LICENSEE "AS IS" AND WITH ALL FAULTS AND DEFECTS WITHOUT WARRANTY OF ANY KIND.  TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, LICENSOR, ON ITS OWN BEHALF AND ON BEHALF OF ITS AFFILIATES, RESELLERS, AND ITS AND THEIR RESPECTIVE LICENSORS AND SERVICE PROVIDERS, EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO THE SOFTWARE, DOCUMENTATION, AND APPROVED HARDWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND WARRANTIES THAT MAY ARISE OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE, USAGE, OR TRADE PRACTICE. WITHOUT LIMITATION TO THE FOREGOING, THE LICENSOR PROVIDES NO WARRANTY OR UNDERTAKING, AND MAKES NO REPRESENTATION OF ANY KIND THAT THE LICENSED SOFTWARE WILL MEET THE LICENSEE’S REQUIREMENTS, ACHIEVE ANY INTENDED RESULTS, BE COMPATIBLE, OR WORK WITH ANY OTHER SOFTWARE, APPLICATIONS, SYSTEMS, OR SERVICES, OPERATE WITHOUT INTERRUPTION, MEET ANY PERFORMANCE OR RELIABILITY STANDARDS OR BE ERROR FREE, OR THAT ANY ERRORS OR DEFECTS CAN OR WILL BE CORRECTED.
Limitation of Liability. TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW:
IN NO EVENT WILL LICENSOR OR ITS AFFILIATES, RESELLERS, OR ANY OF ITS OR THEIR RESPECTIVE LICENSORS OR SERVICE PROVIDERS, BE LIABLE TO LICENSEE OR ANY THIRD PARTY FOR ANY USE, INTERRUPTION, DELAY, OR INABILITY TO USE THE SOFTWARE; LOST REVENUES OR PROFITS; DELAYS, INTERRUPTION, OR LOSS OF SERVICES, BUSINESS, OR GOODWILL; LOSS OR CORRUPTION OF DATA; LOSS RESULTING FROM SYSTEM OR SYSTEM SERVICE FAILURE, MALFUNCTION, OR SHUTDOWN; FAILURE TO ACCURATELY TRANSFER, READ, OR TRANSMIT INFORMATION; FAILURE TO UPDATE OR PROVIDE CORRECT INFORMATION; SYSTEM INCOMPATIBILITY OR PROVISION OF INCORRECT COMPATIBILITY INFORMATION; OR BREACHES IN SYSTEM SECURITY; OR FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, EXEMPLARY, SPECIAL, OR PUNITIVE DAMAGES, WHETHER ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), OR OTHERWISE, REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE AND WHETHER OR NOT THE LICENSOR WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
IN NO EVENT WILL LICENSOR'S AND ITS AFFILIATES', RESELLERS’, INCLUDING ANY OF ITS OR THEIR RESPECTIVE LICENSORS' AND SERVICE PROVIDERS', COLLECTIVE AGGREGATE LIABILITY UNDER OR IN CONNECTION WITH THIS AGREEMENT OR ITS SUBJECT MATTER, UNDER ANY LEGAL OR EQUITABLE THEORY, INCLUDING BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, AND OTHERWISE, EXCEED THE TOTAL AMOUNT PAID TO THE LICENSOR OR RESELLER, AS THE CASE MAY BE, PURSUANT TO THIS AGREEMENT FOR (i) THE SOFTWARE OR (ii) UP TO TWELVE (12) MONTHS OF THE SPECIFIC SERVICES, THAT IS OR ARE THE SUBJECT OF THE CLAIM.
THE LIMITATIONS SET FORTH IN SECTION 12(a) AND SECTION 12(b) SHALL APPLY EVEN IF THE LICENSEE’S REMEDIES UNDER THIS AGREEMENT FAIL OF THEIR ESSENTIAL PURPOSE.
Indemnification.
Licensor Indemnification.  Licensor shall indemnify, defend and hold harmless Licensee and Licensee’s officers, directors, and employees (each, a “Licensee Indemnitee”) from and against any and all claims, actions, or losses incurred by them arising out of or relating to any action by a third party (other than an affiliate of Licensee or a Licensee Indemnitee) to the extent that such claims, actions, or losses arise from an allegation that the Licensee’s exercise of its license rights under this Agreement infringes a Third Party’s United States Intellectual Property Right.  The foregoing obligation does not apply to any claim, action, or loss arising out of or relating to any:
materials, software, or other information supplied to Licensee by a Third Party;
patents issued on any patent application published in the United States after the Effective Date;
incorporation of any Software with or into, or any combination, operation or use of any Software in or with, any technology (including any software, hardware, firmware, system or network), material or service (other than Approved Hardware) not provided by Licensor or specified for Licensee’s use under this Agreement or Documentation, unless otherwise expressly permitted by Licensor in writing;
Licensee’s products or components;
modification of any Software other than: (i) by Licensor; or (ii) with Licensor’s express written approval and in strict accordance with Licensor’s written directions and specifications;
failure to timely implement any Updates, maintenance release, modification, new version, or replacement of the Software made available to Licensee;
use of any Software after Licensor’s notice to Licensee of such activity’s alleged or actual infringement, misappropriation or other violation of a Third Party's rights;
negligence, abuse, misapplication or misuse of any Software by or on behalf of Licensee, or an affiliate or representative of Licensee or a Third Party;
use of any Software by or on behalf of Licensee that is outside the purpose, scope or manner of use authorized by this Agreement or in any manner contrary to Licensor’s instructions or Documentation;
events or circumstances outside of Licensor’s commercially reasonable control (including any Third Party hardware, software or system bugs, defects or malfunctions);
allegation of facts that, if true, would constitute Licensee’s breach of any of its representations, warranties, covenants or obligations under this Agreement; or
act, omission or other subject matter described in Section 13(b), whether or not the same results in any claim or action against or loss by any Licensor Indemnitee.
Licensee Indemnification.  Licensee shall indemnify, defend and hold harmless Licensor and its affiliates, and each of its and their respective members, officers, directors, employees, agents, successors and permitted assigns (each, a "Licensor Indemnitee") from and against any and all claims, actions, or losses incurred by Licensor or any Licensor Indemnitee in connection with any claim, action, or loss alleged by a third party (other than an affiliate of a Licensor Indemnitee) to the extent such claim, action or loss arises from any allegation concerning or relating to:
Any Licensee trademarks, products or components, provided that, where such Licensee trademarks, products or components incorporate or are used or combined with the Software, and such claim, action or loss does not arise solely out of or relate solely to the Software;
Licensor’s compliance with any specifications or directions provided by or on behalf of Licensee to the extent prepared without any contribution by Licensor;
any facts that, if true, would constitute Licensee’s breach of any of its representations, warranties, covenants, or obligations under this Agreement;
Licensee’s use of Social Media Posts or any Personal Information, including but not limited to, any unauthorized use, publication, disclosure, or loss of the same;
Licensee’s negligence or more culpable act or omission; or
the performance of any support or other services hereunder by or on behalf of Licensor in material compliance with this Agreement.
Indemnification Procedure.  Each party shall promptly notify the other party in writing of any claim, action, or loss for which such party believes it is entitled to be indemnified pursuant to Section 13(a) or Section 13(b), as the case may be.  The party seeking indemnification (the “Indemnitee”) shall cooperate with the other party (the “Indemnitor”) at the Indemnitor’s sole cost and expense.  The Indemnitor shall immediately take control of the defense and investigation of such claim, action, or loss and shall employ counsel of its choice to handle and defend the same, at the Indemnitor’s sole cost and expense.  The Indemnitee’s failure to perform any obligations under this Section 13(c) will not relieve the Indemnitor of its obligations under this Section 13 except to the extent that the Indemnitor can demonstrate that it has been materially prejudiced as a result of such failure.  The Indemnitee may participate in and observe the proceedings at its own cost and expense with counsel of its own choosing.
Mitigation.  If any Software is, or in Licensor’s opinion, may likely be claimed to infringe, misappropriate or otherwise violate any Third Party Intellectual Property Right, or if Licensee’s use of any Software is enjoined or threatened to be enjoined, Licensor may, at its option and sole cost and expense:
obtain the right for Licensee to continue to use the affected Software for its purposes as contemplated by this Agreement;
modify or replace the Software, in whole or in part, to seek to make the Software (as so modified or replaced) non-infringing while providing equivalent features and functionality, in which case such modifications or replacements will constitute Software under this Agreement; or
by written notice to Licensee, terminate the licenses granted to Licensee under this Agreement with respect to all or part of the Software, and require Licensee to immediately cease all use of the Software.
THIS SECTION 13(d) SETS FORTH LICENSEE’S SOLE REMEDIES AND LICENSOR’S SOLE LIABILITY AND OBLIGATION FOR ANY ACTUAL, THREATENED OR ALLEGED CLAIMS THAT THIS AGREEMENT OR ANY SUBJECT MATTER HEREOF (INCLUDING THE SOFTWARE OR ANY OTHER LICENSOR MATERIALS OR PROPERTIES) INFRINGES, MISAPPROPRIATES OR OTHERWISE VIOLATES ANY THIRD PARTY INTELLECTUAL PROPERTY RIGHT.
Confidentiality.
Confidential Information. In connection with this Agreement each party (as the "Disclosing Party") has disclosed and may disclose or make available Confidential Information to the other party (as the "Receiving Party").  Subject to Section 14(b), "Confidential Information" means any information in any form or medium, whether provided orally, in written form, electronic form, or any other form, that the Disclosing Party considers confidential or proprietary, including information consisting of or relating to the Disclosing Party’s technology, software, trade secrets, know-how, business operations, plans, strategies, customers, discussions between the parties, designs, proposals, offers, and pricing, and information with respect to which the Disclosing Party has contractual or other confidentiality obligations, whether or not marked, designated or otherwise identified as “confidential”.  Without limiting the foregoing, all unpublished Documentation, and the terms and existence of this Agreement, including financial terms are and will remain the Confidential Information of Licensor.
Exclusions.  Except for Personal Information or any third-party information that the Receiving Party is under a contractual or other binding obligation to maintain in confidence, Confidential Information does not include information that the Receiving Party can demonstrate by written or other documentary records: (a) was rightfully known to the Receiving Party without restriction on use or disclosure prior to such information's disclosure or being made available to the Receiving Party in connection with this Agreement; (b) was or becomes generally known by the public other than by the Receiving Party’s or any of its Representatives’ noncompliance with this Agreement; (c) was or is received by the Receiving Party on a non-confidential basis from a third party that, to the Receiving Party’s knowledge, was not or is not, at the time of such receipt, under any obligation to maintain its confidentiality; or (d) the Receiving Party can demonstrate by written or other documentary records was or is independently developed by the Receiving Party without reference to or use of any Confidential Information.
Protection of Confidential Information. As a condition to being provided with any disclosure of or access to Confidential Information, the Receiving Party shall, during the Term and for a period of two (2) years thereafter:
not access or use Confidential Information other than as necessary to exercise its rights or perform its obligations under and in accordance with this Agreement;
except as may be permitted by and subject to its compliance with Section 14(c)(iv), not disclose or permit access to Confidential Information other than to its Representatives who: (i) need to know such Confidential Information for purposes of the Receiving Party's exercise of its rights or performance of its obligations under and in accordance with this Agreement; (ii) have been informed of the confidential nature of the Confidential Information and the Receiving Party's obligations under this Section 14; and (iii) are bound by confidentiality and restricted use obligations at least as protective of the Confidential Information as the terms set forth in this Section 14;
safeguard the Confidential Information from unauthorized use, access or disclosure using at least the degree of care it uses to protect its similarly sensitive information and in no event less than a reasonable degree of care; and
ensure its representatives’ compliance with, and be responsible and liable for any of its representatives’ non-compliance with, the terms of this Section 10.
If the Receiving Party or any of its representatives is compelled by applicable Law to disclose any Confidential Information then, to the extent permitted by applicable Law, the Receiving Party shall: (a) promptly, and prior to such disclosure, notify the Disclosing Party in writing of such requirement so that the Disclosing Party can seek a protective order or other remedy or waive its rights under Section 14(c); and (b) provide reasonable assistance to the Disclosing Party, at the Disclosing Party's sole cost and expense, in opposing such disclosure or seeking a protective order or other limitations on disclosure. If the Disclosing Party waives compliance or, after providing the notice and assistance required under this Section 14(c)(iv), the Receiving Party remains required by law to disclose any Confidential Information, the Receiving Party shall disclose only that portion of the Confidential Information that the Receiving Party is legally required to disclose and, upon the Disclosing Party's request, shall use commercially reasonable efforts to obtain assurances from the applicable court or other presiding authority that such Confidential Information will be afforded confidential treatment.
Miscellaneous.
Force Majeure.  Licensor will not be responsible or liable to Licensee, or deemed in default or breach hereunder by reason of any failure or delay in the performance of its obligations hereunder where such failure or delay is due to strikes, labor disputes, civil disturbances, riot, rebellion, invasion, epidemic, hostilities, war, terrorist attack, embargo, natural disaster, acts of God, flood, fire, sabotage, fluctuations or non-availability of electrical power, heat, light, air conditioning, or Licensee equipment, loss and destruction of property, or any other circumstances or causes beyond Licensor's reasonable control.
Further Assurances. Upon a party's reasonable request, the other party shall, at the requesting party's sole cost and expense, execute and deliver all such documents and instruments, and take all such further actions, necessary to give full effect to this Agreement.
Relationship of the Parties. The relationship between the parties is that of independent contractors.  Nothing contained in this Agreement shall be construed as creating any agency, partnership, joint venture or other form of joint enterprise, employment or fiduciary relationship between the parties, and neither party shall have authority to contract for or bind the other party in any manner whatsoever.
Public Announcements. Neither party shall issue or release any announcement, statement, press release or other publicity or marketing materials relating to this Agreement or otherwise use the other party's trademarks, service marks, trade names, logos, domain names or other indicia of source, affiliation or sponsorship, in each case, without the prior written consent of the other party, which consent shall not be unreasonably withheld, conditioned or delayed, provided, however, that Licensor may, without Licensee's consent, include Licensee's name and/or other indicia in its lists of Licensor's current or former Licensees of Licensor in promotional and marketing materials.
Notices. Except as otherwise expressly set forth in this Agreement, all notices, requests, consents, claims, demands, waivers and other communications under this Agreement have binding legal effect only if in writing and addressed to a party at the party’s address set forth above (or to such other address or such other person that such party may designate from time to time).  Notices sent in accordance with this Section 15(e) will be deemed effectively given: (a) when received, if delivered by hand, with signed confirmation of receipt; (b) when received, if sent by a nationally recognized overnight courier, signature required; (c) when sent, if by facsimile or e-mail, (in each case, with confirmation of transmission), if sent during the addressee’s normal business hours, and on the next business day, if sent after the addressee’s normal business hours; and (d) on the fifth (5th) day after the date mailed by certified or registered mail, return receipt requested, postage prepaid.
Interpretation. For purposes of this Agreement: (a) the words "include," "includes" and "including" are deemed to be followed by the words "without limitation"; (b) the word "or" is not exclusive; (c) the words "herein," "hereof," "hereby," "hereto" and "hereunder" refer to this Agreement as a whole; (d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa; and (e) words denoting any gender include all genders. Unless the context otherwise requires, references in this Agreement: (x) to sections, exhibits, schedules, attachments and appendices mean the sections of, and exhibits, schedules, attachments and appendices attached to, this Agreement; (y) to an agreement, instrument or other document means such agreement, instrument or other document as amended, supplemented and modified from time to time to the extent permitted by the provisions thereof; and (z) to a statute means such statute as amended from time to time and includes any successor legislation thereto and any regulations promulgated thereunder. The parties intend this Agreement to be construed without regard to any presumption or rule requiring construction or interpretation against the party drafting an instrument or causing any instrument to be drafted. The exhibits, schedules, attachments and appendices referred to herein are an integral part of this Agreement to the same extent as if they were set forth verbatim herein.
Headings. The headings in this Agreement are for reference only and do not affect the interpretation of this Agreement.
Entire Agreement. This Agreement, together with any other documents incorporated herein by reference, constitutes the sole and entire agreement of the parties with respect to the subject matter of this Agreement and supersedes all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to such subject matter.  In the event of any inconsistency between the statements made in the body of this Agreement, the related exhibits, schedules, attachments and appendices (other than an exception expressly set forth as such therein) and any other documents incorporated herein by reference, the following order of precedence governs: (a) first, this Agreement, excluding its exhibits, schedules, attachments and appendices; (b) second, the exhibits, schedules, attachments and appendices to this Agreement as of the Effective Date; and (c) third, any other documents incorporated herein by reference.
Assignment.  Licensee shall not assign or otherwise transfer any of its rights, or delegate or otherwise transfer any of its obligations or performance, under this Agreement, in each case whether voluntarily, involuntarily, by operation of law or otherwise, without Licensor's prior written consent, which consent Licensor may give or withhold in its sole discretion.  For purposes of the preceding sentence, and without limiting its generality, any merger, consolidation or reorganization involving Licensee (regardless of whether Licensee is a surviving or disappearing entity) will be deemed to be a transfer of rights, obligations or performance under this Agreement for which Licensor's prior written consent is required.  No delegation or other transfer will relieve Licensee of any of its obligations or performance under this Agreement.  Any purported assignment, delegation or transfer in violation of this Section 15(i) is void. This Agreement is binding upon and inures to the benefit of the parties hereto and their respective permitted successors and assigns. Licensor may assign the Agreement and its rights and obligations hereunder to an affiliate company or to a third party purchaser of substantially all its assets.
Amendment and Modification; Waiver. No amendment to or modification of or rescission, termination or discharge of this Agreement is effective unless it is in writing, identified as an amendment to or rescission, termination or discharge of this Agreement and signed by an authorized representative of each party. No waiver by any party of any of the provisions hereof shall be effective unless explicitly set forth in writing and signed by the party so waiving.  Except as otherwise set forth in this Agreement, no failure to exercise, or delay in exercising, any rights, remedy, power or privilege arising from this Agreement shall operate or be construed as a waiver thereof; nor shall any single or partial exercise of any right, remedy, power or privilege hereunder preclude any other or further exercise thereof or the exercise of any other right, remedy, power or privilege.
Severability. If any provision of this Agreement is invalid, illegal or unenforceable in any jurisdiction, such invalidity, illegality or unenforceability shall not affect any other term or provision of this Agreement or invalidate or render unenforceable such term or provision in any other jurisdiction.  Upon such determination that any term or other provision is invalid, illegal or unenforceable, the parties hereto shall negotiate in good faith to modify this Agreement so as to effect the original intent of the parties as closely as possible in a mutually acceptable manner in order that the transactions contemplated hereby be consummated as originally contemplated to the greatest extent possible.
Governing Law; Submission to Jurisdiction.  This Agreement is governed by and construed in accordance with the internal laws of the State of New York without giving effect to any choice or conflict of law provision or rule that would require or permit the application of the laws of any jurisdiction other than those of the State of New York.  Any legal suit, action or proceeding arising out of or related to this Agreement or the licenses granted hereunder shall be instituted exclusively in the federal courts of the United States or the courts of the State of New York in each case located in the city of New York and County of New York, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such suit, action or proceeding. Service of process, summons, notice or other document by mail to such party's address set forth herein shall be effective service of process for any suit, action or other proceeding brought in any such court.
Waiver of Jury Trial.  Each party irrevocably and unconditionally waives any right it may have to a trial by jury in respect of any legal action arising out of or relating to this Agreement or the transactions contemplated hereby.
Equitable Relief.   Licensee acknowledges and agrees that a breach or threatened breach of its obligations under this Agreement would cause Licensor irreparable harm for which monetary damages would not be an adequate remedy and agrees that, in the event of such breach or threatened breach, Licensor will be entitled to equitable relief, including a restraining order, an injunction, specific performance and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy.  Such remedies are not exclusive and are in addition to all other remedies that may be available at law, in equity or otherwise.
Attorneys' Fees.  In the event that any action, suit, or other legal or administrative proceeding is instituted or commenced by either party hereto against the other party arising out of or related to this Agreement, the prevailing party shall be entitled to recover its reasonable attorneys' fees and court costs from the non-prevailing party.
Counterparts. This Agreement may be executed in counterparts, each of which is deemed an original, but all of which together are deemed to be one and the same agreement. A signed copy of this Agreement delivered by facsimile, e-mail or other means of electronic transmission is deemed to have the same legal effect as delivery of an original signed copy of this Agreement.
This license is subject to all the terms and conditions stated herein. If any terms contained in ANC’s invoices, statements of work or letters of intent are at variance with the terms of this order, the terms of this order shall govern.  No oral agreement or other understanding shall in any way modify or change the terms of this order unless agreed to in writing and signed by ANC.`;
