/**
 * POST /api/agent-skill/export-proposal-pdf
 *
 * Bridge that lets an AnythingLLM agent skill export the SAME ANC-branded
 * proposal PDF the platform UI produces — the one generated by
 * generateProposalPdfServiceV2 (Puppeteer + the real React template).
 *
 * Pattern mirrors /api/projects/[id]/pdf exactly:
 *   1. Fetch the proposal from the DB (including screens + lineItems)
 *   2. Run mapDbProposalToFormSchema to get the ProposalType shape the
 *      PDF service expects
 *   3. Construct a synthetic NextRequest and hand it to
 *      generateProposalPdfServiceV2 directly — no HTTP round-trip, no
 *      auth middleware in the way
 *   4. Save the PDF buffer to /tmp/anc-exports/ and return a public URL
 *
 * Bypasses NextAuth middleware because this path is under /api/agent-skill/.
 * Auth: x-api-key header matching AGENT_SKILL_API_KEY.
 *
 * Request body:
 *   { proposal_id: string }
 *
 * Response:
 *   {
 *     success: true,
 *     proposal_id: string,
 *     filename: "ANC_<Client>_<mode>_<m-d-yyyy>.pdf",
 *     download_url: string,   // rewritten to public URL
 *     size_bytes: number,
 *     client_name: string,
 *     document_mode: string
 *   }
 *
 * NOTE: For proposals created via the agent-skill create-proposal endpoint
 * (which stores line items in clientSummary / pricingDocument instead of
 * structured screens), the PDF will render with the ANC template but the
 * screen-detail sections will be sparse. Full-quality PDFs come from
 * proposals that have real screen data — normally built through the
 * platform estimator or imported from an RFP analysis.
 */

import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { writeFile, mkdir } from "fs/promises";
import path from "path";
import { prisma } from "@/lib/prisma";
import { mapDbProposalToFormSchema } from "@/lib/proposals/mapDbProposalToForm";
import { generateProposalPdfServiceV2 } from "@/services/proposal/server/generateProposalPdfServiceV2";
import { log } from "@/lib/logger";

export const runtime = "nodejs";
export const maxDuration = 300; // Puppeteer startup + render can take a while

const EXPORT_DIR = "/tmp/anc-exports";

function safeFilenamePart(value: string): string {
  return value
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 80);
}

function authorize(request: NextRequest): NextResponse | null {
  const expected = process.env.AGENT_SKILL_API_KEY;
  if (!expected) {
    return NextResponse.json(
      { error: "Service not configured: AGENT_SKILL_API_KEY missing" },
      { status: 503 },
    );
  }
  const provided = request.headers.get("x-api-key");
  if (!provided || provided !== expected) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }
  return null;
}

export async function POST(request: NextRequest) {
  const authError = authorize(request);
  if (authError) return authError;

  let body: { proposal_id?: string };
  try {
    body = await request.json();
  } catch (e) {
    return NextResponse.json(
      { error: "Invalid JSON body: " + (e as Error).message },
      { status: 400 },
    );
  }

  const proposalId = body.proposal_id?.trim();
  if (!proposalId) {
    return NextResponse.json(
      { error: "proposal_id is required" },
      { status: 400 },
    );
  }

  // 1. Fetch the proposal from the DB (match the /api/projects/[id]/pdf shape)
  const project = await prisma.proposal.findUnique({
    where: { id: proposalId },
    include: {
      screens: {
        include: { lineItems: true },
      },
    },
  });

  if (!project) {
    return NextResponse.json(
      { error: `Proposal not found: ${proposalId}` },
      { status: 404 },
    );
  }

  // 2. Map DB → ProposalType the PDF service expects
  const formPayload = mapDbProposalToFormSchema(project);

  // 3. Build a synthetic NextRequest and call the generator directly
  const mockReq = new NextRequest(
    "http://localhost/api/proposals/generate",
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(formPayload),
    },
  );

  let pdfResponse: Response;
  try {
    pdfResponse = await generateProposalPdfServiceV2(mockReq);
  } catch (err) {
    log.error("[agent-skill/export-proposal-pdf] generator threw:", err);
    return NextResponse.json(
      {
        error: "PDF generation failed",
        details: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }

  if (pdfResponse.status !== 200) {
    const errorBody = await pdfResponse.json().catch(() => ({}));
    log.error(
      "[agent-skill/export-proposal-pdf] non-200 from generator:",
      errorBody,
    );
    return NextResponse.json(
      {
        error:
          typeof errorBody?.error === "string"
            ? errorBody.error
            : "PDF generation failed",
        guidance: Array.isArray(errorBody?.guidance)
          ? errorBody.guidance
          : undefined,
      },
      { status: pdfResponse.status },
    );
  }

  const bytes = await pdfResponse.arrayBuffer();
  if (bytes.byteLength === 0) {
    return NextResponse.json(
      { error: "Generated PDF is empty" },
      { status: 500 },
    );
  }

  // 4. Save to the shared export directory + build a public URL
  await mkdir(EXPORT_DIR, { recursive: true });

  const now = new Date();
  const datePart = `${now.getMonth() + 1}-${now.getDate()}-${now.getFullYear()}`;
  const clientPart = safeFilenamePart(project.clientName || "Project");
  const displayFilename = `ANC_${clientPart}_${project.documentMode}_${datePart}.pdf`;
  // The downloader lives at /api/agent-skill/download-excel but only serves
  // .xlsx. For PDFs we need a separate download endpoint, OR we can serve
  // directly here by returning raw bytes. Since the existing bridges (for
  // Excel) use the shared /tmp/anc-exports dir + download-excel pattern, and
  // download-excel filters by .xlsx only, use a UUID-prefixed name and a
  // dedicated download URL pattern that's PDF-safe.
  const storageFilename = `proposal-${randomUUID()}.pdf`;
  const filePath = path.join(EXPORT_DIR, storageFilename);
  await writeFile(filePath, Buffer.from(bytes));

  const publicBase =
    process.env.NEXT_PUBLIC_BASE_URL || "https://proposals.anc.com";
  // We expose a small download-pdf endpoint in the same bridge namespace.
  // Until that's added, callers can use the stable filename to fetch it
  // via /api/agent-skill/download-pdf?file=<storageFilename>.
  const downloadUrl = `${publicBase}/api/agent-skill/download-pdf?file=${storageFilename}`;

  log.info(
    `[agent-skill/export-proposal-pdf] generated ${storageFilename} (${bytes.byteLength} bytes) for proposal ${proposalId}`,
  );

  return NextResponse.json(
    {
      success: true,
      proposal_id: proposalId,
      filename: displayFilename,
      storage_filename: storageFilename,
      download_url: downloadUrl,
      size_bytes: bytes.byteLength,
      client_name: project.clientName,
      document_mode: project.documentMode,
    },
    { status: 200 },
  );
}
