/**
 * POST /api/agent-skill/export-scoping-workbook
 *
 * Bridge endpoint that returns the SAME scoping workbook Excel the platform
 * UI produces — generated by generateScopingWorkbook(), the shared module
 * used by both the RFP pipeline and the estimator's unified export.
 *
 * Bypasses NextAuth middleware because this path is under /api/agent-skill/.
 *
 * Accepts one of two input shapes (JSON body):
 *
 *   A. Estimator-style input:
 *      {
 *        estimator_answers: EstimatorAnswers  // same object the wizard produces
 *      }
 *      → runs mapEstimatorToScoping(answers) → generateScopingWorkbook()
 *
 *   B. Raw scoping options (power users / already-mapped data):
 *      {
 *        scoping_options: ScopingWorkbookOptions
 *      }
 *      → runs generateScopingWorkbook(scoping_options) directly
 *
 * Auth: x-api-key header matching AGENT_SKILL_API_KEY (same as the
 * create-proposal bridge).
 *
 * The generated workbook is saved to /tmp/anc-exports/ with a UUID name
 * (same directory and naming convention as /api/agent-skill/generate-excel)
 * so it can be fetched back via /api/agent-skill/download-excel?file=...
 *
 * Response:
 *   {
 *     success: true,
 *     filename: "scoping-{uuid}.xlsx",
 *     download_url: "https://proposals.anc.com/api/agent-skill/download-excel?file=scoping-{uuid}.xlsx",
 *     size_bytes: 123456
 *   }
 */

import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { writeFile, mkdir } from "fs/promises";
import path from "path";
import {
  generateScopingWorkbook,
  type ScopingWorkbookOptions,
} from "@/services/rfp/pipeline/generateScopingWorkbook";
import { mapEstimatorToScoping } from "@/services/rfp/pipeline/estimatorToScopingMapper";
import {
  normalizeEstimatorAnswers,
  type EstimatorAnswers,
} from "@/app/components/estimator/questions";
import { log } from "@/lib/logger";

export const runtime = "nodejs";
export const maxDuration = 120;

const EXPORT_DIR = "/tmp/anc-exports";

function authorize(request: NextRequest): NextResponse | null {
  const expected = process.env.AGENT_SKILL_API_KEY;
  if (!expected) {
    return NextResponse.json(
      { error: "Service not configured: AGENT_SKILL_API_KEY missing" },
      { status: 503 },
    );
  }
  const provided = request.headers.get("x-api-key");
  if (!provided || provided !== expected) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }
  return null;
}

export async function POST(request: NextRequest) {
  const authError = authorize(request);
  if (authError) return authError;

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch (e) {
    return NextResponse.json(
      { error: "Invalid JSON body: " + (e as Error).message },
      { status: 400 },
    );
  }

  // Resolve ScopingWorkbookOptions from whichever input mode the caller used
  let options: ScopingWorkbookOptions;
  try {
    if (body.estimator_answers) {
      const answers = normalizeEstimatorAnswers(
        body.estimator_answers as EstimatorAnswers,
      );
      if (!answers || !answers.displays?.length) {
        return NextResponse.json(
          {
            error:
              "estimator_answers must include at least one display entry.",
          },
          { status: 400 },
        );
      }
      options = mapEstimatorToScoping(answers);
    } else if (body.scoping_options && typeof body.scoping_options === "object") {
      options = body.scoping_options as ScopingWorkbookOptions;
      if (!options.project || !Array.isArray(options.specs) || options.specs.length === 0) {
        return NextResponse.json(
          {
            error:
              "scoping_options must include { project, specs: [...] } at minimum.",
          },
          { status: 400 },
        );
      }
    } else {
      return NextResponse.json(
        {
          error:
            "Provide either { estimator_answers } or { scoping_options }.",
        },
        { status: 400 },
      );
    }
  } catch (e) {
    return NextResponse.json(
      {
        error: "Failed to resolve scoping options: " + (e as Error).message,
      },
      { status: 400 },
    );
  }

  // Run the real generator — same code path the platform uses
  try {
    log.info(
      `[agent-skill/export-scoping-workbook] generating workbook for "${options.project?.projectName ?? "(unnamed)"}"`,
    );
    const { buffer } = await generateScopingWorkbook(options);

    await mkdir(EXPORT_DIR, { recursive: true });
    const filename = `scoping-${randomUUID()}.xlsx`;
    const filePath = path.join(EXPORT_DIR, filename);
    await writeFile(filePath, buffer);

    const publicBase =
      process.env.NEXT_PUBLIC_BASE_URL || "https://proposals.anc.com";
    const downloadUrl = `${publicBase}/api/agent-skill/download-excel?file=${filename}`;

    return NextResponse.json(
      {
        success: true,
        filename,
        download_url: downloadUrl,
        size_bytes: buffer.length,
        project: {
          name: options.project?.projectName ?? null,
          client: options.project?.clientName ?? null,
          displays: options.specs.length,
        },
      },
      { status: 200 },
    );
  } catch (err) {
    log.error("[agent-skill/export-scoping-workbook] failed:", err);
    return NextResponse.json(
      {
        error: "Workbook generation failed",
        details: err instanceof Error ? err.message : String(err),
      },
      { status: 500 },
    );
  }
}
